### 회원가입 테스트
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "final@test.com",
  "password": "1234",
  "nickname": "SuccessMan"
}

### 로그인 테스트
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "final@test.com",
  "password": "1234"
}